# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-14 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_assign_q'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='about_pro',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='image',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='name',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='seller_id',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='seller_name',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='seller_price',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='sh_id',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='total',
        ),
        migrations.AddField(
            model_name='piece',
            name='status',
            field=models.CharField(default='fresh', max_length=200),
        ),
    ]
