# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-15 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_piece_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pc_id',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
