# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-17 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_transaction_pc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='amount',
            field=models.CharField(default='300', max_length=200),
        ),
    ]
