# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-17 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20210617_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='about_pro',
            field=models.CharField(default='300', max_length=200),
        ),
        migrations.AddField(
            model_name='piece',
            name='brand',
            field=models.CharField(default='300', max_length=200),
        ),
        migrations.AddField(
            model_name='piece',
            name='total',
            field=models.IntegerField(default=100),
        ),
    ]
